### ISSUE TITLE
参数取值不知道在什么地方

### ISSUE THREAD

**Issue by spring59** [Samler-Lee/ecloud_computer_auto_boot#1]
大佬 这个脚本支持移动云电脑政企版本还是普通的公众版本，参数的取值地方可以说明下在什么地方取吗？

**Comment by halcyon0S** [comment]
同样的问题，大佬这个参数如何取值啊

**Comment by Samler-Lee** [comment]
@halcyon0S @spring59 目前这个版本还不能支持公众版，这也是我后来才发现的，支持公众版的目前正在做，最近比较忙，所以回复很晚，抱歉哈

![image](https://github.com/user-attachments/assets/069169fe-4955-4639-9911-b60f619c6d61)

**Comment by Samler-Lee** [comment]
@spring59 @halcyon0S 适配公众版的代码已推送，欢迎体验，有问题随时反馈

**Comment by spring59** [comment]
> @spring59 @halcyon0S 适配公众版的代码已推送，欢迎体验，有问题随时反馈

多谢大佬  期待加入家庭版

**Comment by ludashi2020** [comment]
政企版那个SK在哪获取啊？AK可以抓包看到，但是SK在哪获取？
