### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by mufengyian** [Samler-Lee/ecloud_computer_auto_boot#2]
请问还能编译吗？我这边gitlab.ecloud.com打不开了

**Comment by Samler-Lee** [comment]
你好，这个是移动云那边的文档关于Golang SDK的安装说明要求的，gitlab.ecloud.com确实是不能直接访问的
另外这个repo目前仅支持政企版，个人版的暂时没有支持，目前已经抓到了相关的包，后续会更新个人版的

**Comment by Samler-Lee** [comment]
关于移动云SDK相关的依赖，最好先按照要求手动安装好再编译

**Comment by mufengyian** [comment]
好的，谢谢大佬，那我公众版的就先不折腾了

**Comment by Samler-Lee** [comment]
[1.0.0](https://github.com/Samler-Lee/ecloud_computer_auto_boot/releases/tag/1.0.0) 已发布，支持公众版账号进行监控，欢迎体验
![image](https://github.com/user-attachments/assets/80de667b-821a-4fbb-a0f2-c56457f6a4b3)

**Comment by mufengyian** [comment]
用上了，感谢

**Comment by mufengyian** [comment]
> [1.0.0](https://github.com/Samler-Lee/ecloud_computer_auto_boot/releases/tag/1.0.0) 已发布，支持公众版账号进行监控，欢迎体验 ![image](https://private-user-images.githubusercontent.com/26178720/384073370-80de667b-821a-4fbb-a0f2-c56457f6a4b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTkxOTEsIm5iZiI6MTczMTA1ODg5MSwicGF0aCI6Ii8yNjE3ODcyMC8zODQwNzMzNzAtODBkZTY2N2ItODIxYS00ZmJiLWEwZjItYzU2NDU3ZjZhNGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA5NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNjIzMzc3MzYzZTcxMjBjMWIyY2Y3N2ZhNDZhN2ExYzJiNjc3MWRjNmQ0YmI2YTYzOGM4ZTEzOWNlMWRhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jEN1xTyJmzcYD2rZhNNomyo9W7r-6U1gV8M9-fOqgx4)

大佬可以加个隔一段时间自动连接一次的功能吗？这样就直接不会关机了，现在好像是检测到关机再开机？

**Comment by Samler-Lee** [comment]
> > [1.0.0](https://github.com/Samler-Lee/ecloud_computer_auto_boot/releases/tag/1.0.0) 已发布，支持公众版账号进行监控，欢迎体验 ![image](https://private-user-images.githubusercontent.com/26178720/384073370-80de667b-821a-4fbb-a0f2-c56457f6a4b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTkxOTEsIm5iZiI6MTczMTA1ODg5MSwicGF0aCI6Ii8yNjE3ODcyMC8zODQwNzMzNzAtODBkZTY2N2ItODIxYS00ZmJiLWEwZjItYzU2NDU3ZjZhNGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA5NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNjIzMzc3MzYzZTcxMjBjMWIyY2Y3N2ZhNDZhN2ExYzJiNjc3MWRjNmQ0YmI2YTYzOGM4ZTEzOWNlMWRhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jEN1xTyJmzcYD2rZhNNomyo9W7r-6U1gV8M9-fOqgx4)
> 
> 
> 
> 大佬可以加个隔一段时间自动连接一次的功能吗？这样就直接不会关机了，现在好像是检测到关机再开机？

这个功能可以考虑一下，但是有可能会对正常使用造成影响

**Comment by mufengyian** [comment]
> > > [1.0.0](https://github.com/Samler-Lee/ecloud_computer_auto_boot/releases/tag/1.0.0) 已发布，支持公众版账号进行监控，欢迎体验 ![image](https://private-user-images.githubusercontent.com/26178720/384073370-80de667b-821a-4fbb-a0f2-c56457f6a4b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTkxOTEsIm5iZiI6MTczMTA1ODg5MSwicGF0aCI6Ii8yNjE3ODcyMC8zODQwNzMzNzAtODBkZTY2N2ItODIxYS00ZmJiLWEwZjItYzU2NDU3ZjZhNGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA5NDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNjIzMzc3MzYzZTcxMjBjMWIyY2Y3N2ZhNDZhN2ExYzJiNjc3MWRjNmQ0YmI2YTYzOGM4ZTEzOWNlMWRhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jEN1xTyJmzcYD2rZhNNomyo9W7r-6U1gV8M9-fOqgx4)
> > 
> > 
> > 大佬可以加个隔一段时间自动连接一次的功能吗？这样就直接不会关机了，现在好像是检测到关机再开机？
> 
> 这个功能可以考虑一下，但是有可能会对正常使用造成影响

好的，影响的话，或许可以和”machines:“参数一样，需要设置自动连接的用户把machine id填进去，之后就按任务执行间隔连接。
