### ISSUE TITLE
依赖无法获取

### ISSUE THREAD

**Issue by NONGFAH** [Samler-Lee/ecloud_computer_auto_boot#4]
gitlab.ecloud.com 域名已经失效

```
go: ecloud_computer_auto_boot/cmd imports
        gitlab.ecloud.com/ecloud/ecloudsdkcomputer: unrecognized import path "gitlab.ecloud.com/ecloud/ecloudsdkcomputer": https fetch: Get "https://gitlab.ecloud.com/ecloud/ecloudsdkcomputer?go-get=1": dial tcp: lookup gitlab.ecloud.com: no such host
go: ecloud_computer_auto_boot/cmd imports
        gitlab.ecloud.com/ecloud/ecloudsdkcomputer/model: unrecognized import path "gitlab.ecloud.com/ecloud/ecloudsdkcomputer": https fetch: Get "https://gitlab.ecloud.com/ecloud/ecloudsdkcomputer?go-get=1": dial tcp: lookup gitlab.ecloud.com: no such host
go: ecloud_computer_auto_boot/cmd imports
        gitlab.ecloud.com/ecloud/ecloudsdkcore/config: unrecognized import path "gitlab.ecloud.com/ecloud/ecloudsdkcore": https fetch: Get "https://gitlab.ecloud.com/ecloud/ecloudsdkcore?go-get=1": dial tcp: lookup gitlab.ecloud.com: no such host
```

**Comment by Samler-Lee** [comment]
关于云电脑SDK的部分，README中有所提及，需要设置GOPROXY和GONOSUMDB后进行安装

**Comment by NONGFAH** [comment]
```
PS C:\Users\master\Desktop\ecloud_computer_auto_boot> go env -w GOPROXY=https://ecloud.10086.cn/api/query/developer/nexus/repository/go-sdk/
PS C:\Users\master\Desktop\ecloud_computer_auto_boot> go env -w GONOSUMDB=gitlab.ecloud.com
PS C:\Users\master\Desktop\ecloud_computer_auto_boot> go get -u gitlab.ecloud.com/ecloud/ecloudsdkcomputer
go: downloading gitlab.ecloud.com/ecloud/ecloudsdkcore v1.0.4
verifying gitlab.ecloud.com/ecloud/ecloudsdkcore@v1.0.4: checksum mismatch
        downloaded: h1:urxnNmqZU9hyQG13ApfYfot5tyqMBUxguvnzYNmIoGA=
        go.sum:     h1:rQSNTeQY4R9SRoTUBxTIkc2eqpHKLGgunUb2pJwGmlg=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
PS C:\Users\master\Desktop\ecloud_computer_auto_boot>
```

**Comment by Samler-Lee** [comment]
> ```
> 
> PS C:\Users\master\Desktop\ecloud_computer_auto_boot> go env -w GOPROXY=https://ecloud.10086.cn/api/query/developer/nexus/repository/go-sdk/
> 
> PS C:\Users\master\Desktop\ecloud_computer_auto_boot> go env -w GONOSUMDB=gitlab.ecloud.com
> 
> PS C:\Users\master\Desktop\ecloud_computer_auto_boot> go get -u gitlab.ecloud.com/ecloud/ecloudsdkcomputer
> 
> go: downloading gitlab.ecloud.com/ecloud/ecloudsdkcore v1.0.4
> 
> verifying gitlab.ecloud.com/ecloud/ecloudsdkcore@v1.0.4: checksum mismatch
> 
>         downloaded: h1:urxnNmqZU9hyQG13ApfYfot5tyqMBUxguvnzYNmIoGA=
> 
>         go.sum:     h1:rQSNTeQY4R9SRoTUBxTIkc2eqpHKLGgunUb2pJwGmlg=
> 
> 
> 
> SECURITY ERROR
> 
> This download does NOT match an earlier download recorded in go.sum.
> 
> The bits may have been replaced on the origin server, or an attacker may
> 
> have intercepted the download attempt.
> 
> 
> 
> For more information, see 'go help module-auth'.
> 
> PS C:\Users\master\Desktop\ecloud_computer_auto_boot>
> 
> ```

删除go.sum中有关gitlab.ecloud.com所有的行后再安装试试
